### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by felix0080** [y123456yz/Reading-and-comprehense-redis-cluster#2]
我想使用github直接看，看不了，用什么编辑软件也看不了，mac没有souceinsight,不能用。你这个项目真让人 蛋疼1

**Comment by y123456yz** [comment]
你需要做转码，我这啥windows，网页和si工具都正常，你的根据你们实际工具做下转码，转码软件网上可以找下，很多的

**Comment by felix0080** [comment]
好吧，只能这样了
